project:
  type: website
  output-dir: docs

website:
  title: "Cleveland Community Cat Project"
  description: ""
  favicon: images/Eartip_Black.png
  
  navbar:
    pinned: true
    
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: donate.qmd
        text: Donate
      - href: requesthelp.qmd
        text: Request Help
      - href: adopt.qmd
        text: Adopt
      - href: foster.qmd
        text: Foster
      - href: volunteer.qmd
        text: Volunteer
      - href: team.qmd
        text: Leadership Team
      - href: resources.qmd
        text: Resources
      - href: data.qmd
        text: Data
 
    right:
      - icon: instagram
        href: https://www.instagram.com/clecatproject/
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61551479930876
      - icon: envelope
        aria-label: email
        href: "mailto:help@communitycatproject.org"  

  page-footer:
    center: |
      © 2026 Cleveland Community Cat Project, a 501(c)(3) nonprofit organization (EIN: 88-3868710)<br>
      [help@communitycatproject.org](mailto:help@communitycatproject.org) • (216) 309-2680<br>
      [@CLEcatproject](https://www.instagram.com/clecatproject/) • [Facebook](https://www.facebook.com/profile.php?id=61551479930876) • [Petfinder](https://www.petfinder.com/search/pets-for-adoption/us/oh/southeuclid/?shelterRescue=5e184747-cbcb-4a03-b836-6b663298a21d&distance=anywhere&sort=oldest_addition)
      

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    canonical-url: true

editor: visual