---
title: "Caretaking"
---

# Winter Shelter
For feral cats living in Cleveland and surrounding areas, winter shelters are crucial to help community cats thrive in low temperatures. Winter shelters for cats should be insulated, compact, and waterproof. Avoid using towels or blankets inside your shelter. When cats lie on a flat material, it draws their body heat out, making it harder for them to stay warm. Cats will be warmer if you use dry insulating material, such as straw (not hay) or shredded newspaper. You can purchase straw bedding in bulk at Tractor Supply, Lowes, Home Depot, or Ace Hardware. In extreme cold, you can attach Mylar blankets to the interior shelter walls using a non-toxic glue (such as Weldbond Universal Adhesive) or freezer tape. Place the shelter in a location where cats are already used to going. They will be more likely to use the shelter if it is near their feeding station, in a location they are familiar with.

We've partnered with local businesses to recycle styrofoam coolers and turn them into insulated feral cat houses. We are pleased to be able to offer these to members of our community. You can request one using the link below!

[Request an Insulated Feral Cat House](https://form.jotform.com/233407948788171)


# Caretaking Tips
When caring for community cats, it is almost always better to do something, even imperfectly, than to do nothing at all. Community Cat Project suggests following these general principles to help protect community cats:

Learn about community cat management and the local resources available to you. Talk to your neighbors and educate others about protecting community cats and reducing their population.

Stay aware of the community cats in your neighborhood. Notice when an unowned cat is injured or not ear-tipped (not neutered/spayed). Intervene in whatever capacity you can.

Provide food and water for cats. Establish a feeding schedule. Set out fresh food and water at the same time every day. Keep feeding spaces clean to deter wildlife and respect your neighborhood environment.

Every situation is different. Not everyone has the time or resources to devote to caring for community cats regularly, but anyone can do a little. 

If you can't trap and transport an injured cat yourself, notify a local rescue group. You will still be helping a cat who might otherwise not receive help.

If you can't feed every day, feeding every two or three days will still provide nutrition for a cat who might otherwise go without food.

If you can't feed cats regularly, set out fresh water. You will still be helping a cat stay hydrated who might otherwise not find water.

Feeding and Watering
Feral cats often depend on humans to survive. You may not know it, but your neighbors probably feed the same cats you do. Feral cats in neighborhoods rarely subsist solely on food they catch themselves, and finding a water source is usually challenging. Feeding and watering is an important way to help reduce intercat aggression over food, maintain healthy outdoor cats, and discourage hunting of local wildlife for food. 

Provide the best food you can comfortably afford. [What's the best food to give feral cats?](https://cats.com/best-cat-food-for-feral-cats)