---
title: "Request Help with Community Cats"
---

Please complete our **Request Help Form** if:

- You found a large colony of cats.
- Multiple cats appear sick or injured.
- The colony is reproducing rapidly.
- You are caring for a colony and need additional guidance.
- The situation is beyond what you can safely manage on your own.

For one or two healthy community cats on private property, we recommend doing TNR on your own. You can learn about this on our [Resources](https://www.clecatproject.org/resources) page.

::: callout-important
**Please note:** Cleveland Community Cat Project is an all-volunteer organization. Our volunteers donate their time without compensation because they care about cats and their community. We have [zero tolerance]{.underline} for abusive, threatening, harassing, or disrespectful behavior toward our volunteers. Our priority is protecting our volunteers above all else. If you engage in this type of conduct, we will end all communication and decline to provide assistance.
:::

[Request Form](https://form.jotform.com/233584882215159){.main-button}

```{=html}
<div class="jotform-wrapper">

<iframe
  id="JotFormIFrame-233584882215159"
  title="Request Form"
  allowtransparency="true"
  allow="geolocation; microphone; camera; fullscreen"
  src="https://form.jotform.com/233584882215159"
  frameborder="0"
  style="
    min-width:100%;
    max-width:100%;
    height:1200px;
    border:none;
  "
  scrolling="no">
</iframe>

</div>

<script type="text/javascript">
var ifr = document.getElementById("JotFormIFrame-233584882215159");

if (ifr) {
  window.addEventListener("message", function(e) {
    if (typeof e.data === 'string' && e.data.indexOf("setHeight") > -1) {
      var height = e.data.split(":")[1];
      ifr.style.height = height + "px";
    }
  }, false);
}
</script>
    
```
